/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    backbup002: THREE.Mesh;
    Cube072: THREE.Mesh;
    Cube072_1: THREE.Mesh;
    Computer001: THREE.Mesh;
    Plane: THREE.Mesh;
    Computer: THREE.Mesh;
    Table: THREE.Mesh;
    Cube002_1: THREE.Mesh;
    Cube002_2: THREE.Mesh;
    TableBottom: THREE.Mesh;
    Drawer: THREE.Mesh;
    Trashcan: THREE.Mesh;
    Drawer002: THREE.Mesh;
    TrashBin: THREE.Mesh;
    TrashPaddle: THREE.Mesh;
    Potted_plants002: THREE.Mesh;
    Potted_plants001: THREE.Mesh;
    Table001: THREE.Mesh;
    Cube004: THREE.Mesh;
    Cube001: THREE.Mesh;
    Cube008: THREE.Mesh;
    Cube003: THREE.Mesh;
    Cube011: THREE.Mesh;
    Cube006: THREE.Mesh;
    Cube014: THREE.Mesh;
    Cube010: THREE.Mesh;
    Cube017: THREE.Mesh;
    Cube013: THREE.Mesh;
    Drawer001: THREE.Mesh;
    Cube020: THREE.Mesh;
    Cube016: THREE.Mesh;
    Torus001: THREE.Mesh;
    Cube019: THREE.Mesh;
    Potted_plants: THREE.Mesh;
    Cube023: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube022: THREE.Mesh;
    Table002: THREE.Mesh;
    Cube005: THREE.Mesh;
    Cube029: THREE.Mesh;
    Cube027: THREE.Mesh;
    Table003: THREE.Mesh;
    Cube009: THREE.Mesh;
    Cube025: THREE.Mesh;
    Cube032: THREE.Mesh;
    Cube034: THREE.Mesh;
    Cube035: THREE.Mesh;
    Cube044: THREE.Mesh;
    Cube012: THREE.Mesh;
    Table007: THREE.Mesh;
    Cube038: THREE.Mesh;
    Cube037: THREE.Mesh;
    Cube045: THREE.Mesh;
    Cube015: THREE.Mesh;
    Cube042: THREE.Mesh;
    Cube041: THREE.Mesh;
    Cube048: THREE.Mesh;
    Sphere: THREE.Mesh;
    Cube057: THREE.Mesh;
    Cube018: THREE.Mesh;
    Cube059: THREE.Mesh;
    Cylinder: THREE.Mesh;
    Cube024: THREE.Mesh;
    Table006: THREE.Mesh;
    Cube021: THREE.Mesh;
    Cube028: THREE.Mesh;
    Table004: THREE.Mesh;
    Cube040: THREE.Mesh;
    Plane003: THREE.Mesh;
    Cube047: THREE.Mesh;
    Cube026: THREE.Mesh;
    Cube055: THREE.Mesh;
    Cube056: THREE.Mesh;
    Circle: THREE.Mesh;
    Cube058: THREE.Mesh;
    Cube060: THREE.Mesh;
    Cube031: THREE.Mesh;
    Cube051: THREE.Mesh;
    Cube063: THREE.Mesh;
    cat: THREE.Mesh;
    Cube052: THREE.Mesh;
    rock002: THREE.Mesh;
    rock: THREE.Mesh;
    Cube033: THREE.Mesh;
    rock004: THREE.Mesh;
    rock007: THREE.Mesh;
    rock001: THREE.Mesh;
    rock009: THREE.Mesh;
    rock003: THREE.Mesh;
    Cube036: THREE.Mesh;
    rock005: THREE.Mesh;
    Plane001: THREE.Mesh;
    rock006: THREE.Mesh;
    Plane002: THREE.Mesh;
    Cube039: THREE.Mesh;
    rock008: THREE.Mesh;
    Plane005: THREE.Mesh;
    rock010: THREE.Mesh;
    Plane006: THREE.Mesh;
    rock012: THREE.Mesh;
    Cube007: THREE.Mesh;
    Cube: THREE.Mesh;
    rock014: THREE.Mesh;
    Cylinder001: THREE.Mesh;
    Fish: THREE.Mesh;
    Cube030: THREE.Mesh;
    Cube043: THREE.Mesh;
    Plane008: THREE.Mesh;
    Cube065: THREE.Mesh;
    Cube050: THREE.Mesh;
    Cube062: THREE.Mesh;
    Table005: THREE.Mesh;
    Cube054: THREE.Mesh;
    Cube046: THREE.Mesh;
    Cube049: THREE.Mesh;
    Cube066: THREE.Mesh;
    Cube061: THREE.Mesh;
    Cube001_7001: THREE.Mesh;
    Cube001_7001_1: THREE.Mesh;
    Cube001_7001_2: THREE.Mesh;
    Cube067: THREE.Mesh;
    Plane004: THREE.Mesh;
    rock011: THREE.Mesh;
    rock013: THREE.Mesh;
    Cube053: THREE.Mesh;
    Plane007: THREE.Mesh;
    Cylinder004: THREE.Mesh;
    Cylinder004_1: THREE.Mesh;
    Cylinder004_2: THREE.Mesh;
    Cylinder004_3: THREE.Mesh;
    Cylinder003: THREE.Mesh;
    Cube001_0006: THREE.Mesh;
    Cube001_0006_1: THREE.Mesh;
    Cube001_0006_2: THREE.Mesh;
    Cube001_0006_3: THREE.Mesh;
    Cube064: THREE.Mesh;
    Cube001_7002: THREE.Mesh;
    Cube001_7002_1: THREE.Mesh;
    Cube001_7002_2: THREE.Mesh;
  };
  materials: {
    ["Potted_plants.004"]: THREE.MeshPhysicalMaterial;
    ["Material.004"]: THREE.MeshPhysicalMaterial;
    ["TableTop.002"]: THREE.MeshPhysicalMaterial;
    TableLeg: THREE.MeshPhysicalMaterial;
    ["Material.002"]: THREE.MeshPhysicalMaterial;
    TableTop: THREE.MeshPhysicalMaterial;
    TableLegBlack: THREE.MeshPhysicalMaterial;
    ["Material.001"]: THREE.MeshPhysicalMaterial;
    Material: THREE.MeshPhysicalMaterial;
    ["Potted_plants.001"]: THREE.MeshPhysicalMaterial;
    ["Potted_plants.002"]: THREE.MeshPhysicalMaterial;
    ["TableTop.001"]: THREE.MeshPhysicalMaterial;
    Potted_plants: THREE.MeshPhysicalMaterial;
    ["Pink plants"]: THREE.MeshPhysicalMaterial;
    Books: THREE.MeshPhysicalMaterial;
    ["Material.003"]: THREE.MeshPhysicalMaterial;
    ["TableTop.003"]: THREE.MeshPhysicalMaterial;
    ["TableLeg.001"]: THREE.MeshPhysicalMaterial;
    Glass: THREE.MeshPhysicalMaterial;
    Rock: THREE.MeshPhysicalMaterial;
    ["Books.001"]: THREE.MeshPhysicalMaterial;
    ["Books.003"]: THREE.MeshPhysicalMaterial;
    ["Books.002"]: THREE.MeshPhysicalMaterial;
    ["Material.016"]: THREE.MeshStandardMaterial;
    ["Material.009"]: THREE.MeshStandardMaterial;
    ["Material.010"]: THREE.MeshStandardMaterial;
    ["Potted_plants.003"]: THREE.MeshPhysicalMaterial;
    ["Material.012"]: THREE.MeshStandardMaterial;
    ["Material.011"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ActionName = "FishAction.001";

export default function Room(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "/Room-draco.glb"
  ) as unknown as GLTFResult;
  const { actions, names } = useAnimations(animations, group);
  console.log(names);
  useEffect(() => {
    actions[names[0]]?.reset().fadeIn(0.5).play();
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Torus"
          position={[-1.58, 1.29, -0.08]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={0.12}
        />
        <mesh
          name="backbup002"
          castShadow
          receiveShadow
          geometry={nodes.backbup002.geometry}
          material={materials["Potted_plants.004"]}
          position={[1.14, 0, 2.74]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 3.38, 1]}
        />
        <group name="backbup" rotation={[Math.PI, 0, Math.PI]}>
          <mesh
            name="Cube072"
            castShadow
            receiveShadow
            geometry={nodes.Cube072.geometry}
            material={materials["Potted_plants.004"]}
          />
          <mesh
            name="Cube072_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube072_1.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <mesh
          name="Computer001"
          castShadow
          receiveShadow
          geometry={nodes.Computer001.geometry}
          material={materials["TableTop.002"]}
          position={[-1.69, 1.49, 0.82]}
          scale={[0.02, 0.26, 0.45]}
        />
        <mesh
          name="Plane"
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials.TableLeg}
          position={[-1.28, 2.11, -1.89]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.54, 0.2, 0.86]}
        />
        <mesh
          name="Computer"
          castShadow
          receiveShadow
          geometry={nodes.Computer.geometry}
          material={materials["Material.002"]}
          position={[-1.69, 1.49, 0.82]}
          scale={[0.02, 0.26, 0.45]}
        />
        <mesh
          name="Table"
          castShadow
          receiveShadow
          geometry={nodes.Table.geometry}
          material={materials.TableTop}
          position={[-1.48, 1.03, 0.71]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <group
          name="TableLeg"
          position={[-1.48, 1, -0.34]}
          rotation={[Math.PI, 0, Math.PI]}
        >
          <mesh
            name="Cube002_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube002_1.geometry}
            material={materials.TableLeg}
          />
          <mesh
            name="Cube002_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube002_2.geometry}
            material={materials.TableLegBlack}
          />
        </group>
        <mesh
          name="TableBottom"
          castShadow
          receiveShadow
          geometry={nodes.TableBottom.geometry}
          material={materials.TableLeg}
          position={[-1.48, 0.27, -0.34]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          name="Drawer"
          castShadow
          receiveShadow
          geometry={nodes.Drawer.geometry}
          material={materials.TableTop}
          position={[-1.35, 1.01, 1.44]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          name="Trashcan"
          castShadow
          receiveShadow
          geometry={nodes.Trashcan.geometry}
          material={materials["Material.001"]}
          position={[-1.45, 0.32, 1.44]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          name="Drawer002"
          castShadow
          receiveShadow
          geometry={nodes.Drawer002.geometry}
          material={materials.TableLeg}
          position={[-0.24, 1.81, -0.09]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          name="TrashBin"
          castShadow
          receiveShadow
          geometry={nodes.TrashBin.geometry}
          material={materials.Material}
          position={[-1.45, 0.47, 1.44]}
          rotation={[Math.PI, 0, 2.94]}
          scale={[0.98, 0.13, 1.01]}
        />
        <mesh
          name="TrashPaddle"
          castShadow
          receiveShadow
          geometry={nodes.TrashPaddle.geometry}
          material={materials["TableTop.002"]}
          position={[-1.28, 0.23, 1.43]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1, 0.15, 1]}
        />
        <mesh
          name="Potted_plants002"
          castShadow
          receiveShadow
          geometry={nodes.Potted_plants002.geometry}
          material={materials["Potted_plants.001"]}
          position={[-1.48, 0.19, -1.38]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.02}
        />
        <mesh
          name="Potted_plants001"
          castShadow
          receiveShadow
          geometry={nodes.Potted_plants001.geometry}
          material={materials["Potted_plants.002"]}
          position={[-1.48, 0.19, -1.38]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.02}
        />
        <mesh
          name="Table001"
          castShadow
          receiveShadow
          geometry={nodes.Table001.geometry}
          material={materials["TableTop.001"]}
          position={[-0.42, 1.52, -0.09]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          name="Cube004"
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Cube001"
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Cube008"
          castShadow
          receiveShadow
          geometry={nodes.Cube008.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Cube003"
          castShadow
          receiveShadow
          geometry={nodes.Cube003.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Cube011"
          castShadow
          receiveShadow
          geometry={nodes.Cube011.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Cube006"
          castShadow
          receiveShadow
          geometry={nodes.Cube006.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Cube014"
          castShadow
          receiveShadow
          geometry={nodes.Cube014.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Cube010"
          castShadow
          receiveShadow
          geometry={nodes.Cube010.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Cube017"
          castShadow
          receiveShadow
          geometry={nodes.Cube017.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Cube013"
          castShadow
          receiveShadow
          geometry={nodes.Cube013.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Drawer001"
          castShadow
          receiveShadow
          geometry={nodes.Drawer001.geometry}
          material={materials.TableTop}
          position={[-0.24, 1.81, -0.09]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          name="Cube020"
          castShadow
          receiveShadow
          geometry={nodes.Cube020.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Cube016"
          castShadow
          receiveShadow
          geometry={nodes.Cube016.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Torus001"
          castShadow
          receiveShadow
          geometry={nodes.Torus001.geometry}
          material={materials.TableLegBlack}
          position={[-1.59, 1.29, -0.08]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={0.44}
        />
        <mesh
          name="Cube019"
          castShadow
          receiveShadow
          geometry={nodes.Cube019.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Potted_plants"
          castShadow
          receiveShadow
          geometry={nodes.Potted_plants.geometry}
          material={materials.Potted_plants}
          position={[-1.48, 0.19, -1.38]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.02}
        />
        <mesh
          name="Cube023"
          castShadow
          receiveShadow
          geometry={nodes.Cube023.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Cube002"
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Cube022"
          castShadow
          receiveShadow
          geometry={nodes.Cube022.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Table002"
          castShadow
          receiveShadow
          geometry={nodes.Table002.geometry}
          material={materials["TableTop.002"]}
          position={[-1.4, 1.06, 0.87]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.25, 0.25, 0.19]}
        />
        <mesh
          name="Cube005"
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Cube029"
          castShadow
          receiveShadow
          geometry={nodes.Cube029.geometry}
          material={materials["Material.002"]}
          position={[-1.56, 1.07, 1.03]}
          rotation={[0, 0, -0.03]}
          scale={[0.03, 0, 0.01]}
        />
        <mesh
          name="Cube027"
          castShadow
          receiveShadow
          geometry={nodes.Cube027.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Table003"
          castShadow
          receiveShadow
          geometry={nodes.Table003.geometry}
          material={materials["TableTop.002"]}
          position={[-1.38, 1.06, 0.37]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.32, 0.07, 0.17]}
        />
        <mesh
          name="Cube009"
          castShadow
          receiveShadow
          geometry={nodes.Cube009.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Cube025"
          castShadow
          receiveShadow
          geometry={nodes.Cube025.geometry}
          material={materials.TableLeg}
          position={[-1.63, 1.1, 1.36]}
          scale={[0.03, 0.05, 0.03]}
        />
        <mesh
          name="Cube032"
          castShadow
          receiveShadow
          geometry={nodes.Cube032.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Cube034"
          castShadow
          receiveShadow
          geometry={nodes.Cube034.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Cube035"
          castShadow
          receiveShadow
          geometry={nodes.Cube035.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Cube044"
          castShadow
          receiveShadow
          geometry={nodes.Cube044.geometry}
          material={materials.TableTop}
          position={[-1.67, 3.16, 0.71]}
        />
        <mesh
          name="Cube012"
          castShadow
          receiveShadow
          geometry={nodes.Cube012.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Table007"
          castShadow
          receiveShadow
          geometry={nodes.Table007.geometry}
          material={materials.TableTop}
          position={[-1.75, 1.19, -1.33]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.3, 1, 0.17]}
        />
        <mesh
          name="Cube038"
          castShadow
          receiveShadow
          geometry={nodes.Cube038.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Cube037"
          castShadow
          receiveShadow
          geometry={nodes.Cube037.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Cube045"
          castShadow
          receiveShadow
          geometry={nodes.Cube045.geometry}
          material={materials["Pink plants"]}
          position={[-1.64, 2.5, 0.51]}
        />
        <mesh
          name="Cube015"
          castShadow
          receiveShadow
          geometry={nodes.Cube015.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Cube042"
          castShadow
          receiveShadow
          geometry={nodes.Cube042.geometry}
          material={materials["Material.002"]}
          position={[-1.5, 1.07, 1.04]}
          rotation={[0, 0, -0.03]}
          scale={[0.01, 0.01, 0.02]}
        />
        <mesh
          name="Cube041"
          castShadow
          receiveShadow
          geometry={nodes.Cube041.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Cube048"
          castShadow
          receiveShadow
          geometry={nodes.Cube048.geometry}
          material={materials.Books}
          position={[-1.7, 2.61, 1.18]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        />
        <mesh
          name="Sphere"
          castShadow
          receiveShadow
          geometry={nodes.Sphere.geometry}
          material={materials["Material.002"]}
          position={[-1.38, 1.06, 0.37]}
          scale={[0.05, 0.02, 0.05]}
        />
        <mesh
          name="Cube057"
          castShadow
          receiveShadow
          geometry={nodes.Cube057.geometry}
          material={materials["Material.003"]}
          position={[-1.7, 2.6, 1.02]}
          rotation={[-1.08, 1.54, 0.05]}
        />
        <mesh
          name="Cube018"
          castShadow
          receiveShadow
          geometry={nodes.Cube018.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Cube059"
          castShadow
          receiveShadow
          geometry={nodes.Cube059.geometry}
          material={materials.Books}
          position={[-1.7, 2.61, 1.15]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        />
        <mesh
          name="Cylinder"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={materials.Material}
          position={[-1.58, 1.18, -0.08]}
          scale={[1, 2.42, 1]}
        />
        <mesh
          name="Cube024"
          castShadow
          receiveShadow
          geometry={nodes.Cube024.geometry}
          material={materials["Material.002"]}
          position={[-1.18, 1.06, 0.99]}
          rotation={[1.55, 1.54, -1.55]}
          scale={[0.03, 0, 0.01]}
        />
        <mesh
          name="Table006"
          castShadow
          receiveShadow
          geometry={nodes.Table006.geometry}
          material={materials.TableTop}
          position={[-1.75, 1.06, -0.75]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.3, 1, 0.04]}
        />
        <mesh
          name="Cube021"
          castShadow
          receiveShadow
          geometry={nodes.Cube021.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Cube028"
          castShadow
          receiveShadow
          geometry={nodes.Cube028.geometry}
          material={materials["Potted_plants.002"]}
          position={[-1.64, 1.14, 1.34]}
          rotation={[-0.14, -0.13, 0.05]}
          scale={[0, 0.04, 0]}
        />
        <mesh
          name="Table004"
          castShadow
          receiveShadow
          geometry={nodes.Table004.geometry}
          material={materials.TableTop}
          position={[-1.65, 2.46, 0.71]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.58, 1, 0.64]}
        />
        <mesh
          name="Cube040"
          castShadow
          receiveShadow
          geometry={nodes.Cube040.geometry}
          material={materials.Material}
          position={[-1.63, 1.13, 1.35]}
          rotation={[-0.47, 0, 0.03]}
          scale={[0, 0.04, 0]}
        />
        <mesh
          name="Plane003"
          castShadow
          receiveShadow
          geometry={nodes.Plane003.geometry}
          material={materials["Material.002"]}
          position={[-0.33, 0.81, 0.82]}
        />
        <mesh
          name="Cube047"
          castShadow
          receiveShadow
          geometry={nodes.Cube047.geometry}
          material={materials.Books}
          position={[-1.7, 2.61, 1.18]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        />
        <mesh
          name="Cube026"
          castShadow
          receiveShadow
          geometry={nodes.Cube026.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Cube055"
          castShadow
          receiveShadow
          geometry={nodes.Cube055.geometry}
          material={materials["Material.003"]}
          position={[-1.58, 2.55, 0.39]}
          rotation={[0.08, 0.46, -0.17]}
        />
        <mesh
          name="Cube056"
          castShadow
          receiveShadow
          geometry={nodes.Cube056.geometry}
          material={materials["Material.003"]}
          position={[-1.64, 2.5, 0.51]}
        />
        <mesh
          name="Circle"
          castShadow
          receiveShadow
          geometry={nodes.Circle.geometry}
          material={materials["TableTop.003"]}
          position={[-0.23, 0.73, 0.8]}
          scale={[0.06, 0.07, 0.06]}
        />
        <mesh
          name="Cube058"
          castShadow
          receiveShadow
          geometry={nodes.Cube058.geometry}
          material={materials["Material.003"]}
          position={[-1.7, 2.61, 1.18]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        />
        <mesh
          name="Cube060"
          castShadow
          receiveShadow
          geometry={nodes.Cube060.geometry}
          material={materials["Material.003"]}
          position={[-1.7, 2.61, 1.15]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        />
        <mesh
          name="Cube031"
          castShadow
          receiveShadow
          geometry={nodes.Cube031.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="Cube051"
          castShadow
          receiveShadow
          geometry={nodes.Cube051.geometry}
          material={materials.TableTop}
          position={[1, 0.69, -1.26]}
          scale={[1.03, 0.22, 0.55]}
        />
        <mesh
          name="Cube063"
          castShadow
          receiveShadow
          geometry={nodes.Cube063.geometry}
          material={materials["Material.003"]}
          position={[-1.7, 2.61, 1.12]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        />
        <mesh
          name="cat"
          castShadow
          receiveShadow
          geometry={nodes.cat.geometry}
          material={materials["TableLeg.001"]}
          position={[-1.55, 3.07, 0.71]}
          rotation={[Math.PI / 2, 0, -2.99]}
          scale={0.01}
        />
        <mesh
          name="Cube052"
          castShadow
          receiveShadow
          geometry={nodes.Cube052.geometry}
          material={materials.Glass}
          position={[1, 0.69, -1.26]}
          scale={[1.03, 0.22, 0.55]}
        />
        <mesh
          name="rock002"
          castShadow
          receiveShadow
          geometry={nodes.rock002.geometry}
          material={materials.Rock}
          position={[0.59, 1.03, -1.46]}
          scale={0.24}
        />
        <mesh
          name="rock"
          castShadow
          receiveShadow
          geometry={nodes.rock.geometry}
          material={materials.Rock}
          position={[0.32, 1.02, -1.29]}
          scale={0.23}
        />
        <mesh
          name="Cube033"
          castShadow
          receiveShadow
          geometry={nodes.Cube033.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="rock004"
          castShadow
          receiveShadow
          geometry={nodes.rock004.geometry}
          material={materials.Rock}
          position={[0.94, 1.04, -1.5]}
          scale={[0.16, 0.11, 0.11]}
        />
        <mesh
          name="rock007"
          castShadow
          receiveShadow
          geometry={nodes.rock007.geometry}
          material={materials.Rock}
          position={[0.74, 0.97, -1]}
          scale={0.11}
        />
        <mesh
          name="rock001"
          castShadow
          receiveShadow
          geometry={nodes.rock001.geometry}
          material={materials.Rock}
          position={[0.34, 0.98, -1.04]}
          scale={0.11}
        />
        <mesh
          name="rock009"
          castShadow
          receiveShadow
          geometry={nodes.rock009.geometry}
          material={materials.Rock}
          position={[1.39, 1.01, -1.5]}
          rotation={[0, -1.36, 0]}
          scale={[0.06, 0.08, 0.1]}
        />
        <mesh
          name="rock003"
          castShadow
          receiveShadow
          geometry={nodes.rock003.geometry}
          material={materials.Rock}
          position={[0.43, 1.13, -1.43]}
          rotation={[0.37, 0.34, 0.78]}
          scale={0.42}
        />
        <mesh
          name="Cube036"
          castShadow
          receiveShadow
          geometry={nodes.Cube036.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="rock005"
          castShadow
          receiveShadow
          geometry={nodes.rock005.geometry}
          material={materials.Rock}
          position={[0.58, 0.98, -1.15]}
          rotation={[-0.01, 0.68, 1.29]}
          scale={0.19}
        />
        <mesh
          name="Plane001"
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials["Books.001"]}
          position={[-0.33, 0.81, 0.81]}
        />
        <mesh
          name="rock006"
          castShadow
          receiveShadow
          geometry={nodes.rock006.geometry}
          material={materials.Rock}
          position={[1.07, 0.96, -1.1]}
          rotation={[0.55, 0.68, 0.6]}
          scale={0.24}
        />
        <mesh
          name="Plane002"
          castShadow
          receiveShadow
          geometry={nodes.Plane002.geometry}
          material={materials.Potted_plants}
          position={[0.97, 1.03, -0.9]}
          rotation={[Math.PI / 2, -1.57, 0]}
          scale={0.12}
        />
        <mesh
          name="Cube039"
          castShadow
          receiveShadow
          geometry={nodes.Cube039.geometry}
          material={materials["Material.002"]}
          position={[-1.47, 1.07, 1.05]}
          rotation={[0, 0, -0.03]}
          scale={0.01}
        />
        <mesh
          name="rock008"
          castShadow
          receiveShadow
          geometry={nodes.rock008.geometry}
          material={materials.Rock}
          position={[1.24, 0.96, -0.85]}
          scale={[0.35, 0.1, 0.18]}
        />
        <mesh
          name="Plane005"
          castShadow
          receiveShadow
          geometry={nodes.Plane005.geometry}
          material={materials.Potted_plants}
          position={[1.56, 1.03, -0.99]}
          rotation={[Math.PI / 2, -1.57, 0]}
          scale={0.12}
        />
        <mesh
          name="rock010"
          castShadow
          receiveShadow
          geometry={nodes.rock010.geometry}
          material={materials.Rock}
          position={[1.66, 1, -1.07]}
          rotation={[-1.87, -0.02, -2.45]}
          scale={[0.24, 0.21, 0.21]}
        />
        <mesh
          name="Plane006"
          castShadow
          receiveShadow
          geometry={nodes.Plane006.geometry}
          material={materials.Potted_plants}
          position={[1.68, 1.03, -1.17]}
          rotation={[Math.PI / 2, -1.57, 0]}
          scale={0.12}
        />
        <mesh
          name="rock012"
          castShadow
          receiveShadow
          geometry={nodes.rock012.geometry}
          material={materials.Rock}
          position={[1.71, 0.99, -1.58]}
          rotation={[1.83, 0.9, -0.39]}
          scale={[0.29, 0.11, 0.15]}
        />
        <mesh
          name="Cube007"
          castShadow
          receiveShadow
          geometry={nodes.Cube007.geometry}
          material={materials["Material.002"]}
          position={[-1.43, 1.07, 0.87]}
          rotation={[0, 0, -0.03]}
          scale={[0.01, 0.01, 0.06]}
        />
        <mesh
          name="Cube"
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials["Pink plants"]}
          position={[0.14, 0.92, -1.03]}
          scale={0.03}
        />
        <mesh
          name="rock014"
          castShadow
          receiveShadow
          geometry={nodes.rock014.geometry}
          material={materials.Rock}
          position={[1.41, 0.95, -1.07]}
          rotation={[1.98, 1.16, -0.57]}
          scale={[0.12, 0.12, 0.2]}
        />
        <mesh
          name="Cylinder001"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials.TableLegBlack}
          position={[-1.58, 1.18, -0.08]}
          scale={[1, 2.42, 1]}
        />
        <mesh
          name="Fish"
          castShadow
          receiveShadow
          geometry={nodes.Fish.geometry}
          material={materials.Material}
          position={[1.5, 1.32, -0.94]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.05}
        />
        <mesh
          name="Cube030"
          castShadow
          receiveShadow
          geometry={nodes.Cube030.geometry}
          material={materials.Potted_plants}
          position={[-1.64, 1.13, 1.36]}
          rotation={[-0.21, -0.14, 0.23]}
          scale={[0, 0.04, 0]}
        />
        <mesh
          name="Cube043"
          castShadow
          receiveShadow
          geometry={nodes.Cube043.geometry}
          material={materials["TableTop.002"]}
          position={[-1.62, 1.13, 1.37]}
          rotation={[0.57, 0.72, -0.17]}
          scale={[0, 0.04, 0]}
        />
        <mesh
          name="Plane008"
          castShadow
          receiveShadow
          geometry={nodes.Plane008.geometry}
          material={materials.Glass}
          position={[0.86, 0.19, 2.47]}
          scale={0.65}
        />
        <mesh
          name="Cube065"
          castShadow
          receiveShadow
          geometry={nodes.Cube065.geometry}
          material={materials["Books.003"]}
          position={[1.34, 0.19, 3.14]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.1, 0, 0.19]}
        />
        <mesh
          name="Cube050"
          castShadow
          receiveShadow
          geometry={nodes.Cube050.geometry}
          material={materials.TableTop}
          position={[-1.47, 3.37, 0.5]}
          rotation={[-Math.PI, 1.57, 0]}
        />
        <mesh
          name="Cube062"
          castShadow
          receiveShadow
          geometry={nodes.Cube062.geometry}
          material={nodes.Cube062.material}
          position={[1.51, 0.51, 2.67]}
          scale={[0.03, 0.01, 0.01]}
        />
        <mesh
          name="Table005"
          castShadow
          receiveShadow
          geometry={nodes.Table005.geometry}
          material={materials.TableTop}
          position={[-1.75, 2.45, -0.35]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.3, 1, 0.04]}
        />
        <mesh
          name="Cube054"
          castShadow
          receiveShadow
          geometry={nodes.Cube054.geometry}
          material={materials["Pink plants"]}
          position={[1.88, 0.99, -1.53]}
          scale={0.02}
        />
        <mesh
          name="Cube046"
          castShadow
          receiveShadow
          geometry={nodes.Cube046.geometry}
          material={materials.Material}
          position={[-1.58, 2.55, 0.39]}
          rotation={[0.08, 0.46, -0.17]}
        />
        <mesh
          name="Cube049"
          castShadow
          receiveShadow
          geometry={nodes.Cube049.geometry}
          material={materials.Potted_plants}
          position={[-1.7, 2.6, 1.02]}
          rotation={[-1.08, 1.54, 0.05]}
        />
        <mesh
          name="Cube066"
          castShadow
          receiveShadow
          geometry={nodes.Cube066.geometry}
          material={materials["Books.002"]}
          position={[1.22, 0.19, 2.86]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.1, 0, 0.19]}
        />
        <mesh
          name="Cube061"
          castShadow
          receiveShadow
          geometry={nodes.Cube061.geometry}
          material={materials.Books}
          position={[-1.7, 2.61, 1.12]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        />
        <group
          name="Lavanda"
          position={[0.83, 0.3, 3.1]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.43}
        >
          <mesh
            name="Cube001_7001"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_7001.geometry}
            material={materials["Material.016"]}
          />
          <mesh
            name="Cube001_7001_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_7001_1.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            name="Cube001_7001_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_7001_2.geometry}
            material={materials["Material.010"]}
          />
        </group>
        <mesh
          name="Cube067"
          castShadow
          receiveShadow
          geometry={nodes.Cube067.geometry}
          material={materials["Books.001"]}
          position={[1.26, 0.19, 2.59]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.1, 0, 0.19]}
        />
        <mesh
          name="Plane004"
          castShadow
          receiveShadow
          geometry={nodes.Plane004.geometry}
          material={materials.TableLeg}
          position={[-0.27, 0.88, 0.42]}
          scale={[1, 1, 0.7]}
        />
        <mesh
          name="rock011"
          castShadow
          receiveShadow
          geometry={nodes.rock011.geometry}
          material={materials.Rock}
          position={[1.69, 0.96, -0.85]}
          rotation={[-1.65, 0.12, -2.9]}
          scale={[-0.21, -0.06, -0.11]}
        />
        <mesh
          name="rock013"
          castShadow
          receiveShadow
          geometry={nodes.rock013.geometry}
          material={materials.Rock}
          position={[1.89, 0.95, -1.05]}
          rotation={[1.98, 1.16, -0.57]}
          scale={0.11}
        />
        <mesh
          name="Cube053"
          castShadow
          receiveShadow
          geometry={nodes.Cube053.geometry}
          material={materials["Pink plants"]}
          position={[0.84, 0.96, -1.31]}
          scale={[0.02, 0.06, 0.02]}
        />
        <mesh
          name="Plane007"
          castShadow
          receiveShadow
          geometry={nodes.Plane007.geometry}
          material={materials["Pink plants"]}
          position={[0.86, 0.19, 2.47]}
          scale={0.65}
        />
        <group
          name="Cylinder002"
          position={[1.51, 0.45, 2.52]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.09, 0.15, 0.09]}
        >
          <mesh
            name="Cylinder004"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004.geometry}
            material={materials["Potted_plants.003"]}
          />
          <mesh
            name="Cylinder004_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004_1.geometry}
            material={materials.Material}
          />
          <mesh
            name="Cylinder004_2"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004_2.geometry}
            material={materials.TableTop}
          />
          <mesh
            name="Cylinder004_3"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004_3.geometry}
            material={materials.TableTop}
          />
        </group>
        <mesh
          name="Cylinder003"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003.geometry}
          material={materials.TableTop}
          position={[1.51, 0.31, 2.52]}
          scale={[0.02, 0.12, 0.02]}
        />
        <group
          name="Flower"
          position={[0.87, 0.25, 2.98]}
          rotation={[-1.42, 0, 0]}
          scale={0.28}
        >
          <mesh
            name="Cube001_0006"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_0006.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            name="Cube001_0006_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_0006_1.geometry}
            material={materials["Material.012"]}
          />
          <mesh
            name="Cube001_0006_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_0006_2.geometry}
            material={materials["Material.011"]}
          />
          <mesh
            name="Cube001_0006_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_0006_3.geometry}
            material={materials["Material.010"]}
          />
        </group>
        <mesh
          name="Cube064"
          castShadow
          receiveShadow
          geometry={nodes.Cube064.geometry}
          material={materials["Potted_plants.001"]}
          position={[0.85, 0.19, 2.96]}
          scale={[0.12, 0.01, 0.21]}
        />
        <group
          name="Lavanda001"
          position={[0.94, 0.3, 2.87]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.32}
        >
          <mesh
            name="Cube001_7002"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_7002.geometry}
            material={materials["Material.016"]}
          />
          <mesh
            name="Cube001_7002_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_7002_1.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            name="Cube001_7002_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_7002_2.geometry}
            material={materials["Material.010"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Room-draco.glb");
